### ISSUE TITLE
Heightmap creation obstacle

### ISSUE THREAD

**Issue by Ygarr** [FlorianRaediker/world2minetest#1]
Is there source to get ASCII XYZ files for other places, other cities near Europe? Not only Hannover?

**Comment by FlorianRaediker** [comment]
Sorry, I only used this for Hanover so far and have no idea whether other cities provide such data.

If you find a heightmap in another format, you might be able to convert it to ASCII XYZ or change parse_heightmap_xyz.py accordingly to read the files?

**Comment by Ygarr** [comment]
Ok, is this point of the plan necessary? Or can I skip it? (it's okay if the map is still flat for now)

**Comment by FlorianRaediker** [comment]
It should be possible to skip it.
When creating the final map.dat file, just leave out the `--heightmap=parsed_data/heightmap.dat` part. Only one argument is required (`--heightmap`, `--features`, or `--buildings`).

If you run into any other problems, please let me know.

**Comment by Ygarr** [comment]
Only thing I get is .dxf file from web service.
